// Create with some manual editing of the output of:
//   cd ApprovalTests
//   cd find . -name \*.h*

#include "ApprovalTests/ApprovalException.h"
#include "ApprovalTests/ApprovalWriter.h"
#include "ApprovalTests/Approvals.h"
#include "ApprovalTests/Catch2Approvals.h"
#include "ApprovalTests/CombinationApprovals.h"
#include "ApprovalTests/FileApprover.h"
#include "ApprovalTests/FileUtils.h"
#include "ApprovalTests/GoogleTestApprovals.h"
#include "ApprovalTests/Macros.h"
#include "ApprovalTests/OkraApprovals.h"
#include "ApprovalTests/StringUtils.h"
#include "ApprovalTests/StringWriter.h"
#include "ApprovalTests/SystemUtils.h"
#include "ApprovalTests/comparators/ApprovalComparator.h"
#include "ApprovalTests/comparators/TextFileComparator.h"
#include "ApprovalTests/namers/ApprovalNamer.h"
#include "ApprovalTests/namers/ApprovalTestNamer.h"
#include "ApprovalTests/namers/ExistingFileNamer.h"
#include "ApprovalTests/namers/SubdirectoryDisposer.h"
#include "ApprovalTests/reporters/BlockingReporter.h"
#include "ApprovalTests/reporters/ClipboardReporter.h"
#include "ApprovalTests/reporters/CombinationReporter.h"
#include "ApprovalTests/reporters/CommandLauncher.h"
#include "ApprovalTests/reporters/CommandReporter.h"
#include "ApprovalTests/reporters/DefaultFrontLoadedReporter.h"
#include "ApprovalTests/reporters/DefaultReporter.h"
#include "ApprovalTests/reporters/DefaultReporterDisposer.h"
#include "ApprovalTests/reporters/DefaultReporterFactory.h"
#include "ApprovalTests/reporters/DiffInfo.h"
#include "ApprovalTests/reporters/DiffPrograms.h"
#include "ApprovalTests/reporters/DiffReporter.h"
#include "ApprovalTests/reporters/FirstWorkingReporter.h"
#include "ApprovalTests/reporters/FrontLoadedReporterDisposer.h"
#include "ApprovalTests/reporters/FrontLoadedReporterFactory.h"
#include "ApprovalTests/reporters/GenericDiffReporter.h"
#include "ApprovalTests/reporters/LinuxReporters.h"
#include "ApprovalTests/reporters/MacReporters.h"
#include "ApprovalTests/reporters/QuietReporter.h"
#include "ApprovalTests/reporters/Reporter.h"
#include "ApprovalTests/reporters/SystemLauncher.h"
#include "ApprovalTests/reporters/WindowsReporters.h"
#include "ApprovalTests/utilities/Blocker.h"
#include "ApprovalTests/utilities/MachineBlocker.h"
#include "ApprovalTests/writers/ExistingFile.h"
